// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using RidingClubMS.DAL.Models;
using System;

namespace RidingClubMS.DAL.Migrations
{
    [DbContext(typeof(RidingClubMS_DB))]
    [Migration("20180322225057_AddRidesTable")]
    partial class AddRidesTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("RidingClubMS.DAL.Models.Horses", b =>
                {
                    b.Property<int>("HorseId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DateOfBirth");

                    b.Property<string>("HorseBreed")
                        .IsRequired();

                    b.Property<string>("HorseBreeder")
                        .IsRequired();

                    b.Property<string>("HorseCoulour")
                        .IsRequired();

                    b.Property<string>("HorseDam")
                        .IsRequired();

                    b.Property<string>("HorseDescription")
                        .IsRequired();

                    b.Property<string>("HorseName")
                        .IsRequired();

                    b.Property<string>("HorseSex")
                        .IsRequired();

                    b.Property<string>("HorseSire")
                        .IsRequired();

                    b.HasKey("HorseId");

                    b.ToTable("Horses");
                });

            modelBuilder.Entity("RidingClubMS.DAL.Models.Rides", b =>
                {
                    b.Property<int>("RideId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AdvanceLevel");

                    b.Property<int>("AvailablePlaces");

                    b.Property<DateTime>("RideDate");

                    b.Property<string>("RideTime");

                    b.Property<int>("TrainerId");

                    b.HasKey("RideId");

                    b.ToTable("Rides");
                });

            modelBuilder.Entity("RidingClubMS.DAL.Models.Users", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<string>("Password");

                    b.Property<string>("Phone");

                    b.Property<string>("ROLE");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
