// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using RidingClubMS.DAL.Models;
using System;

namespace RidingClubMS.DAL.Migrations
{
    [DbContext(typeof(RidingClubMS_DB))]
    [Migration("20180322222048_AddHorsesTable")]
    partial class AddHorsesTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("RidingClubMS.DAL.Models.Horses", b =>
                {
                    b.Property<int>("HorseId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DateOfBirth");

                    b.Property<string>("HorseBreed")
                        .IsRequired();

                    b.Property<string>("HorseBreeder")
                        .IsRequired();

                    b.Property<string>("HorseCoulour")
                        .IsRequired();

                    b.Property<string>("HorseDam")
                        .IsRequired();

                    b.Property<string>("HorseDescription")
                        .IsRequired();

                    b.Property<string>("HorseName")
                        .IsRequired();

                    b.Property<string>("HorseSex")
                        .IsRequired();

                    b.Property<string>("HorseSire")
                        .IsRequired();

                    b.HasKey("HorseId");

                    b.ToTable("Horses");
                });
#pragma warning restore 612, 618
        }
    }
}
